### ISSUE TITLE
能不能支持移植到MAUI或者wpf上

### ISSUE THREAD

**Issue by XiangZou2** [vipwan/Biwen.QuickApi#4]
能不能支持移植到MAUI或者wpf上

**Comment by vipwan** [comment]
[Biwen.QuickApi](https://github.com/vipwan/Biwen.QuickApi) 属于服务端开发组件,不适用于MAUI等客户端框 😢

**Comment by XiangZou2** [comment]
考不考虑直接对接HttpListener，这样子客户端想开放API也方便一点

**Comment by XiangZou2** [comment]
https://github.com/dotnet/aspnetcore/issues/35077 看这个争论，应该是MAUI以后也会支持Host了

**Comment by vipwan** [comment]
> [dotnet/aspnetcore#35077](https://github.com/dotnet/aspnetcore/issues/35077) 看这个争论，应该是MAUI以后也会支持Host了

这个不确定以后是怎样的, 不过我个人的感觉是 意义不大, Host对环境的要求很高 Android和IOS对后台常驻以及端口是有诸多限制的. 如果只是在win上玩那这个意义也不大. 

另外 MAUI如果开的api只是给自己用的话MAUI+Blazor其实已经可以了
